/** biome-ignore-all lint/suspicious/noExplicitAny: generated by convex */

import type {
  Adapter,
  AdapterAccount,
  AdapterSession,
  AdapterUser,
  VerificationToken,
} from "@auth/core/adapters";
import { api } from "@workspace/backend/_generated/api";
import type { Doc, Id } from "@workspace/backend/_generated/dataModel";
import { fetchMutation, fetchQuery } from "convex/nextjs";
import type { FunctionArgs, FunctionReference } from "convex/server";

type User = AdapterUser & { id: Id<"users"> };
type Session = AdapterSession & { userId: Id<"users"> };
type Account = AdapterAccount & { userId: Id<"users"> };

export const ConvexAdapter: Adapter = {
  async createSession(session: Session) {
    const id = await callMutation(api.adapter.createSession, {
      session: toDB(session),
    });
    return { ...session, id };
  },
  async createUser({ id: _, emailVerified, ...user }: User) {
    const id = await callMutation(api.adapter.createUser, {
      user: toDB({
        ...user,
        plan: "free",
        lastLogin: Date.now(),
      }),
    });
    return { ...user, id, emailVerified: null };
  },
  async createVerificationToken(verificationToken: VerificationToken) {
    await callMutation(api.adapter.createVerificationToken, {
      verificationToken: toDB(verificationToken),
    });
    return verificationToken;
  },
  async deleteSession(sessionToken) {
    return maybeSessionFromDB(
      await callMutation(api.adapter.deleteSession, {
        sessionToken,
      })
    );
  },
  async deleteUser(id: Id<"users">) {
    return maybeUserFromDB(await callMutation(api.adapter.deleteUser, { id }));
  },
  async getAccount(providerAccountId, provider) {
    return (await callQuery(api.adapter.getAccount, {
      provider,
      providerAccountId,
    })) as AdapterAccount;
  },
  async getSessionAndUser(sessionToken) {
    const result = await callQuery(api.adapter.getSessionAndUser, {
      sessionToken,
    });
    if (result === null) {
      return null;
    }
    const { user, session } = result;
    return { user: userFromDB(user), session: sessionFromDB(session) };
  },
  async getUser(id: Id<"users">) {
    return maybeUserFromDB(await callQuery(api.adapter.getUser, { id }));
  },
  async getUserByAccount({ provider, providerAccountId }) {
    return maybeUserFromDB(
      await callQuery(api.adapter.getUserByAccount, {
        provider,
        providerAccountId,
      })
    );
  },
  async getUserByEmail(email) {
    return maybeUserFromDB(
      await callQuery(api.adapter.getUserByEmail, { email })
    );
  },
  async linkAccount(account: Account) {
    return (await callMutation(api.adapter.linkAccount, {
      account,
    })) as AdapterAccount;
  },
  async unlinkAccount({ provider, providerAccountId }) {
    return (await callMutation(api.adapter.unlinkAccount, {
      provider,
      providerAccountId,
    })) as AdapterAccount;
  },
  async updateSession(session: Session) {
    return await callMutation(api.adapter.updateSession, {
      session: toDB(session),
    });
  },
  async updateUser({ emailVerified, ...user }: User) {
    await callMutation(api.adapter.updateUser, { user: toDB(user) });
    return {
      ...user,
      emailVerified: null,
    };
  },
  async useVerificationToken({ identifier, token }) {
    return maybeVerificationTokenFromDB(
      await callMutation(api.adapter.useVerificationToken, {
        identifier,
        token,
      })
    );
  },
};

/// Helpers

function callQuery<Query extends FunctionReference<"query">>(
  query: Query,
  args: Omit<FunctionArgs<Query>, "secret">
) {
  return fetchQuery(query, addSecret(args) as any);
}

function callMutation<Mutation extends FunctionReference<"mutation">>(
  mutation: Mutation,
  args: Omit<FunctionArgs<Mutation>, "secret">
) {
  return fetchMutation(mutation, addSecret(args) as any);
}

if (process.env.CONVEX_AUTH_ADAPTER_SECRET === undefined) {
  throw new Error("Missing CONVEX_AUTH_ADAPTER_SECRET environment variable");
}

function addSecret(args: Record<string, any>) {
  return { ...args, secret: process.env.CONVEX_AUTH_ADAPTER_SECRET };
}

function maybeUserFromDB(user: Doc<"users"> | null) {
  if (user === null) {
    return null;
  }
  return userFromDB(user);
}

function userFromDB(user: Doc<"users">) {
  return {
    ...user,
    id: user._id,
    emailVerified: null,
  };
}

function maybeSessionFromDB(session: Doc<"sessions"> | null) {
  if (session === null) {
    return null;
  }
  return sessionFromDB(session);
}

function sessionFromDB(session: Doc<"sessions">) {
  return { ...session, id: session._id, expires: new Date(session.expires) };
}

function maybeVerificationTokenFromDB(
  verificationToken: Doc<"verificationTokens"> | null
) {
  if (verificationToken === null) {
    return null;
  }
  return verificationTokenFromDB(verificationToken);
}

function verificationTokenFromDB(verificationToken: Doc<"verificationTokens">) {
  return { ...verificationToken, expires: new Date(verificationToken.expires) };
}

function toDB<T extends object>(
  obj: T
): {
  [K in keyof T]: T[K] extends Date
    ? number
    : null extends T[K]
      ? undefined
      : T[K];
} {
  const result: any = {};
  for (const key in obj) {
    const value = obj[key];
    result[key] =
      value instanceof Date
        ? value.getTime()
        : value === null
          ? undefined
          : value;
  }
  return result;
}
